language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.githubusercontent.com/decibel/42f9a449b2bdfbb24cf5/raw/pg-travis-pgxn.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
env:
  # 9.3: https://travis-ci.org/decibel/cat_snap/jobs/117857516
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6
  - PGVERSION=10
  - PGVERSION=11
  - PGVERSION=12
script: bash ./pg-travis-pgxn.sh

# vi: expandtab ts=2 sw=2
